
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from os import environ as osEnvironment

from gitissue2todoist.preferences.Preferences import Preferences
from gitissue2todoist.adapters.HttpxGitHubAdapter import HttpxGitHubAdapter
from gitissue2todoist.adapters.IHttpxGitHubAdapter import AbbreviatedGitIssues
from gitissue2todoist.adapters.IHttpxGitHubAdapter import IntermediateStatus
from gitissue2todoist.adapters.IHttpxGitHubAdapter import IssueOwner
from gitissue2todoist.adapters.IHttpxGitHubAdapter import MilestoneTitles
from gitissue2todoist.adapters.IHttpxGitHubAdapter import Slug
from gitissue2todoist.adapters.IHttpxGitHubAdapter import Slugs

TEST_REPO_NAME:       Slug = Slug('hasii2011/testrepository')
TEST_MILESTONE_TITLE: str  = 'Milestone 2'
EXPECTED_ISSUE_COUNT: int  = 3

TEST_SLUGS: Slugs = Slugs(
    [
        Slug('hasii2011/testrepository'),
        Slug('hasii2011/StarTrekPy'),
        Slug('hasii2011/Chip8Emulator'),
        Slug('hasii2011/buildlackey')
    ]
)

class TestHttpxGitHubAdapter(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 04 June 2026
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

        self._preferences: Preferences = Preferences()

        self._gitHubToken: str = ''
        try:
            self._gitHubToken = osEnvironment['GH_TOKEN']
        except KeyError:
            self.logger.warning(f'GitHub Token not set')


    def tearDown(self):
        super().tearDown()

    def testGetRepositoryNames(self):
        if self._gitHubToken == '':
            self.logger.warning(f'Cannot run test either token or user name not set in environment')
        else:
            adapter: HttpxGitHubAdapter = HttpxGitHubAdapter(authenticationToken=self._gitHubToken)

            slugs: Slugs = adapter.getRepositoryNames()
            self.assertTrue(len(slugs) != 0, 'We should find someting')

    def testGetMileStoneTitles(self):

        if self._gitHubToken == '':
            self.logger.warning(f'Cannot run test either token or user name not set in environment')
        else:
            adapter: HttpxGitHubAdapter = HttpxGitHubAdapter(authenticationToken=self._gitHubToken)

            mileStoneTitles: MilestoneTitles = adapter.getMileStoneTitles(repoName=TEST_REPO_NAME)

            self.assertTrue(len(mileStoneTitles) != 0, 'We should find some milestones')

    def testGetAbbreviatedIssues(self):
        if self._gitHubToken == '':
            self.logger.warning(f'Cannot run test either token or user name not set in environment')
        else:
            adapter: HttpxGitHubAdapter = HttpxGitHubAdapter(authenticationToken=self._gitHubToken)

            abbreviatedGitIssues: AbbreviatedGitIssues = adapter.getAbbreviatedIssues(repoName=TEST_REPO_NAME, milestoneTitle=TEST_MILESTONE_TITLE)

            actualIssueCount: int = len(abbreviatedGitIssues)

            self.assertEqual(EXPECTED_ISSUE_COUNT, actualIssueCount, 'Mismatch on test repo, milestone issues')

    def testGetIssuesAssignedToOwner(self):
        if self._gitHubToken == '':
            self.logger.warning(f'Cannot run test either token or user name not set in environment')
        else:
            adapter: HttpxGitHubAdapter = HttpxGitHubAdapter(authenticationToken=self._gitHubToken)
            abbreviatedGitIssues: AbbreviatedGitIssues = adapter.getIssuesAssignedToOwner(
                slugs=TEST_SLUGS,
                issueOwner=IssueOwner('hasii2011'),
                callback=self._statusCallback
            )
            self.assertTrue(len(abbreviatedGitIssues) !=0, 'We must, we must improve our count')

    def _statusCallback(self, status: IntermediateStatus):
        self.logger.warning(f'{status.nameOfRepoJustProcessed=}')

def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestHttpxGitHubAdapter))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
