
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from os import environ as osEnvironment

from gitissue2todoist.Preferences import Preferences
from gitissue2todoist.adapters.HttpxGitHubAdapter import HttpxGitHubAdapter
from gitissue2todoist.adapters.IGitHubAdapter import MilestoneTitles
from gitissue2todoist.adapters.IGitHubAdapter import Slug
from gitissue2todoist.adapters.IGitHubAdapter import Slugs


class TestHttpxGitHubAdapter(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 04 June 2026
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

        self._preferences: Preferences = Preferences()

        self._gitHubToken: str = ''
        try:
            self._gitHubToken = osEnvironment['GH_TOKEN']
        except KeyError:
            self.logger.warning(f'GitHub Token not set')


    def tearDown(self):
        super().tearDown()

    def testGetRepositoryNames(self):
        if self._gitHubToken == '':
            self.logger.warning(f'Cannot run test either token or user name not set in environment')
        else:
            adapter: HttpxGitHubAdapter = HttpxGitHubAdapter(authenticationToken=self._gitHubToken)

            slugs: Slugs = adapter.getRepositoryNames()
            self.assertTrue(len(slugs) != 0, 'We should find someting')

    def testGetMileStoneTitles(self):

        if self._gitHubToken == '':
            self.logger.warning(f'Cannot run test either token or user name not set in environment')
        else:
            adapter: HttpxGitHubAdapter = HttpxGitHubAdapter(authenticationToken=self._gitHubToken)

            mileStoneTitles: MilestoneTitles = adapter.getMileStoneTitles(repoName=Slug('hasii2011/testrepository'))

            self.assertTrue(len(mileStoneTitles) != 0, 'We should find some milestones')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestHttpxGitHubAdapter))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
