from pathlib import Path
from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from gitissue2todoist.general.ResourceManager import ResourceManager


# import the class you want to test here
# from org.pyut.template import template


class TestResourceManager(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 01 June 2026
    """

    TEST_JSON_LOGGING_CONFIG_FILENAME: str = "testLoggingConfiguration.json"

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testRetrieveResourcePath(self):

        actualPath: Path = ResourceManager.retrieveResourcePath(TestResourceManager.TEST_JSON_LOGGING_CONFIG_FILENAME)

        self.assertIsNotNone(actualPath, 'Need something back')

    def testRetrieveResourceText(self):
        pass


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestResourceManager))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
